[package]
name = "dungeon_crawl"
version = "0.0.1"
edition = "2021"

[dependencies]
bracket-lib = "~0.8.7"
legion = "~0.4.0"
serde = {version = "=1.0.115"}
ron = "=0.6.1"

[profile.release]
lto = "thin"